# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5609e693d30198ab407f6ee3c828eef7b552c14327f754eea533797784d9911bb440bb416422b98d1e0cb2f320ba2d47b720271759603ea110cb2a6a0efe1d65
  ENV["GMAIL_USERNAME"] = ''
  ENV["GMAIL_PASSWORD"] = ''

  ENV["CLIENT_ID"] = '530079316263-8dcpqaoeg3hp3asga08t0th5q03o5lav.apps.googleusercontent.com'
  ENV["CLIENT_SECRET"] = 'eVxNy3K7o88j55ta10pQ9Lx3'
  ENV["ACCESS_TOKEN"] = 'ya29.lgEHGtQQerEtZgLzQlUtPMOqSeo7kC-fcOzhvrgRKZlTR_TrDIA0p6WLJR6LI4H27K37ZHzU6YQfoQ'
  ENV["REFRESH_TOKEN"] =  '1/aElQiV7cm8pEnfYa4N_3YVOc6xY6LOkQEY0bXpPD-f1IgOrJDtdun6zK6XiATCKT'
  ENV['GOOGLE_DRIVE_PUBLIC_FOLDER_ID'] = '0B4QFjHfJ3wAFfm9GY3NWdXlNX2dZQmQzRzZTOGtHSFJ6eVNUTEh0al9RUTk5aG1MT0E3ZFE'

test:
  secret_key_base: 3378a69c8de6e05dc0e3ce379bf9600c8cc31fa79edafe34cdc88670421d8aa3279007e7f2d35e02129d039f920a2486adc2604538c63b6706199a2a134d97f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
