require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EnrolmentsController, type: :controller do
  # login_admin
  before(:each) do
      @request.env["devise.mapping"] = Devise.mappings[:user]
      user = FactoryGirl.create(:student_user)
      user.confirm! # or set a confirmed_at inside the factory. Only necessary if you are using the "confirmable" module
      sign_in user
    end

  # This should return the minimal set of attributes required to create a valid
  # Enrolment. As you add validations to Enrolment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnrolmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let(:enrolment) {FactoryGirl.create(:enrolment)}

  describe "GET #index" do
    it "assigns all enrolments as @enrolments" do
      # enrolment = Enrolment.create! valid_attributes
      get :index
      expect(assigns(:enrolments)).to eq([enrolment])
    end
  end

  describe "GET #show" do
    it "assigns the requested enrolment as @enrolment" do
      enrolment = Enrolment.create! valid_attributes
      get :show, {:id => enrolment.to_param}, valid_session
      expect(assigns(:enrolment)).to eq(enrolment)
    end
  end

  describe "GET #new" do
    it "assigns a new enrolment as @enrolment" do
      get :new, {}
      expect(assigns(:enrolment)).to be_a_new(Enrolment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested enrolment as @enrolment" do
      enrolment = Enrolment.create! valid_attributes
      get :edit, {:id => enrolment.to_param}, valid_session
      expect(assigns(:enrolment)).to eq(enrolment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Enrolment" do
        expect {
          post :create, {:enrolment => valid_attributes}, valid_session
        }.to change(Enrolment, :count).by(1)
      end

      it "assigns a newly created enrolment as @enrolment" do
        post :create, {:enrolment => valid_attributes}, valid_session
        expect(assigns(:enrolment)).to be_a(Enrolment)
        expect(assigns(:enrolment)).to be_persisted
      end

      it "redirects to the created enrolment" do
        post :create, {:enrolment => valid_attributes}, valid_session
        expect(response).to redirect_to(Enrolment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved enrolment as @enrolment" do
        post :create, {:enrolment => invalid_attributes}, valid_session
        expect(assigns(:enrolment)).to be_a_new(Enrolment)
      end

      it "re-renders the 'new' template" do
        post :create, {:enrolment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested enrolment" do
        enrolment = Enrolment.create! valid_attributes
        put :update, {:id => enrolment.to_param, :enrolment => new_attributes}, valid_session
        enrolment.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested enrolment as @enrolment" do
        enrolment = Enrolment.create! valid_attributes
        put :update, {:id => enrolment.to_param, :enrolment => valid_attributes}, valid_session
        expect(assigns(:enrolment)).to eq(enrolment)
      end

      it "redirects to the enrolment" do
        enrolment = Enrolment.create! valid_attributes
        put :update, {:id => enrolment.to_param, :enrolment => valid_attributes}, valid_session
        expect(response).to redirect_to(enrolment)
      end
    end

    context "with invalid params" do
      it "assigns the enrolment as @enrolment" do
        enrolment = Enrolment.create! valid_attributes
        put :update, {:id => enrolment.to_param, :enrolment => invalid_attributes}, valid_session
        expect(assigns(:enrolment)).to eq(enrolment)
      end

      it "re-renders the 'edit' template" do
        enrolment = Enrolment.create! valid_attributes
        put :update, {:id => enrolment.to_param, :enrolment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested enrolment" do
      enrolment = Enrolment.create! valid_attributes
      expect {
        delete :destroy, {:id => enrolment.to_param}, valid_session
      }.to change(Enrolment, :count).by(-1)
    end

    it "redirects to the enrolments list" do
      enrolment = Enrolment.create! valid_attributes
      delete :destroy, {:id => enrolment.to_param}, valid_session
      expect(response).to redirect_to(enrolments_url)
    end
  end

end
