require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LanguageCultureDiversitiesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LanguageCultureDiversity. As you add validations to LanguageCultureDiversity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LanguageCultureDiversitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all language_culture_diversities as @language_culture_diversities" do
      language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:language_culture_diversities)).to eq([language_culture_diversity])
    end
  end

  describe "GET #show" do
    it "assigns the requested language_culture_diversity as @language_culture_diversity" do
      language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
      get :show, {:id => language_culture_diversity.to_param}, valid_session
      expect(assigns(:language_culture_diversity)).to eq(language_culture_diversity)
    end
  end

  describe "GET #new" do
    it "assigns a new language_culture_diversity as @language_culture_diversity" do
      get :new, {}, valid_session
      expect(assigns(:language_culture_diversity)).to be_a_new(LanguageCultureDiversity)
    end
  end

  describe "GET #edit" do
    it "assigns the requested language_culture_diversity as @language_culture_diversity" do
      language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
      get :edit, {:id => language_culture_diversity.to_param}, valid_session
      expect(assigns(:language_culture_diversity)).to eq(language_culture_diversity)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LanguageCultureDiversity" do
        expect {
          post :create, {:language_culture_diversity => valid_attributes}, valid_session
        }.to change(LanguageCultureDiversity, :count).by(1)
      end

      it "assigns a newly created language_culture_diversity as @language_culture_diversity" do
        post :create, {:language_culture_diversity => valid_attributes}, valid_session
        expect(assigns(:language_culture_diversity)).to be_a(LanguageCultureDiversity)
        expect(assigns(:language_culture_diversity)).to be_persisted
      end

      it "redirects to the created language_culture_diversity" do
        post :create, {:language_culture_diversity => valid_attributes}, valid_session
        expect(response).to redirect_to(LanguageCultureDiversity.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved language_culture_diversity as @language_culture_diversity" do
        post :create, {:language_culture_diversity => invalid_attributes}, valid_session
        expect(assigns(:language_culture_diversity)).to be_a_new(LanguageCultureDiversity)
      end

      it "re-renders the 'new' template" do
        post :create, {:language_culture_diversity => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested language_culture_diversity" do
        language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
        put :update, {:id => language_culture_diversity.to_param, :language_culture_diversity => new_attributes}, valid_session
        language_culture_diversity.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested language_culture_diversity as @language_culture_diversity" do
        language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
        put :update, {:id => language_culture_diversity.to_param, :language_culture_diversity => valid_attributes}, valid_session
        expect(assigns(:language_culture_diversity)).to eq(language_culture_diversity)
      end

      it "redirects to the language_culture_diversity" do
        language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
        put :update, {:id => language_culture_diversity.to_param, :language_culture_diversity => valid_attributes}, valid_session
        expect(response).to redirect_to(language_culture_diversity)
      end
    end

    context "with invalid params" do
      it "assigns the language_culture_diversity as @language_culture_diversity" do
        language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
        put :update, {:id => language_culture_diversity.to_param, :language_culture_diversity => invalid_attributes}, valid_session
        expect(assigns(:language_culture_diversity)).to eq(language_culture_diversity)
      end

      it "re-renders the 'edit' template" do
        language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
        put :update, {:id => language_culture_diversity.to_param, :language_culture_diversity => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested language_culture_diversity" do
      language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
      expect {
        delete :destroy, {:id => language_culture_diversity.to_param}, valid_session
      }.to change(LanguageCultureDiversity, :count).by(-1)
    end

    it "redirects to the language_culture_diversities list" do
      language_culture_diversity = LanguageCultureDiversity.create! valid_attributes
      delete :destroy, {:id => language_culture_diversity.to_param}, valid_session
      expect(response).to redirect_to(language_culture_diversities_url)
    end
  end

end
