require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PreTrainingReviewsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PreTrainingReview. As you add validations to PreTrainingReview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PreTrainingReviewsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all pre_training_reviews as @pre_training_reviews" do
      pre_training_review = PreTrainingReview.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pre_training_reviews)).to eq([pre_training_review])
    end
  end

  describe "GET #show" do
    it "assigns the requested pre_training_review as @pre_training_review" do
      pre_training_review = PreTrainingReview.create! valid_attributes
      get :show, {:id => pre_training_review.to_param}, valid_session
      expect(assigns(:pre_training_review)).to eq(pre_training_review)
    end
  end

  describe "GET #new" do
    it "assigns a new pre_training_review as @pre_training_review" do
      get :new, {}, valid_session
      expect(assigns(:pre_training_review)).to be_a_new(PreTrainingReview)
    end
  end

  describe "GET #edit" do
    it "assigns the requested pre_training_review as @pre_training_review" do
      pre_training_review = PreTrainingReview.create! valid_attributes
      get :edit, {:id => pre_training_review.to_param}, valid_session
      expect(assigns(:pre_training_review)).to eq(pre_training_review)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PreTrainingReview" do
        expect {
          post :create, {:pre_training_review => valid_attributes}, valid_session
        }.to change(PreTrainingReview, :count).by(1)
      end

      it "assigns a newly created pre_training_review as @pre_training_review" do
        post :create, {:pre_training_review => valid_attributes}, valid_session
        expect(assigns(:pre_training_review)).to be_a(PreTrainingReview)
        expect(assigns(:pre_training_review)).to be_persisted
      end

      it "redirects to the created pre_training_review" do
        post :create, {:pre_training_review => valid_attributes}, valid_session
        expect(response).to redirect_to(PreTrainingReview.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved pre_training_review as @pre_training_review" do
        post :create, {:pre_training_review => invalid_attributes}, valid_session
        expect(assigns(:pre_training_review)).to be_a_new(PreTrainingReview)
      end

      it "re-renders the 'new' template" do
        post :create, {:pre_training_review => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pre_training_review" do
        pre_training_review = PreTrainingReview.create! valid_attributes
        put :update, {:id => pre_training_review.to_param, :pre_training_review => new_attributes}, valid_session
        pre_training_review.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pre_training_review as @pre_training_review" do
        pre_training_review = PreTrainingReview.create! valid_attributes
        put :update, {:id => pre_training_review.to_param, :pre_training_review => valid_attributes}, valid_session
        expect(assigns(:pre_training_review)).to eq(pre_training_review)
      end

      it "redirects to the pre_training_review" do
        pre_training_review = PreTrainingReview.create! valid_attributes
        put :update, {:id => pre_training_review.to_param, :pre_training_review => valid_attributes}, valid_session
        expect(response).to redirect_to(pre_training_review)
      end
    end

    context "with invalid params" do
      it "assigns the pre_training_review as @pre_training_review" do
        pre_training_review = PreTrainingReview.create! valid_attributes
        put :update, {:id => pre_training_review.to_param, :pre_training_review => invalid_attributes}, valid_session
        expect(assigns(:pre_training_review)).to eq(pre_training_review)
      end

      it "re-renders the 'edit' template" do
        pre_training_review = PreTrainingReview.create! valid_attributes
        put :update, {:id => pre_training_review.to_param, :pre_training_review => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested pre_training_review" do
      pre_training_review = PreTrainingReview.create! valid_attributes
      expect {
        delete :destroy, {:id => pre_training_review.to_param}, valid_session
      }.to change(PreTrainingReview, :count).by(-1)
    end

    it "redirects to the pre_training_reviews list" do
      pre_training_review = PreTrainingReview.create! valid_attributes
      delete :destroy, {:id => pre_training_review.to_param}, valid_session
      expect(response).to redirect_to(pre_training_reviews_url)
    end
  end

end
