require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe VicStudentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # VicStudent. As you add validations to VicStudent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VicStudentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all vic_students as @vic_students" do
      vic_student = VicStudent.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:vic_students)).to eq([vic_student])
    end
  end

  describe "GET #show" do
    it "assigns the requested vic_student as @vic_student" do
      vic_student = VicStudent.create! valid_attributes
      get :show, {:id => vic_student.to_param}, valid_session
      expect(assigns(:vic_student)).to eq(vic_student)
    end
  end

  describe "GET #new" do
    it "assigns a new vic_student as @vic_student" do
      get :new, {}, valid_session
      expect(assigns(:vic_student)).to be_a_new(VicStudent)
    end
  end

  describe "GET #edit" do
    it "assigns the requested vic_student as @vic_student" do
      vic_student = VicStudent.create! valid_attributes
      get :edit, {:id => vic_student.to_param}, valid_session
      expect(assigns(:vic_student)).to eq(vic_student)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new VicStudent" do
        expect {
          post :create, {:vic_student => valid_attributes}, valid_session
        }.to change(VicStudent, :count).by(1)
      end

      it "assigns a newly created vic_student as @vic_student" do
        post :create, {:vic_student => valid_attributes}, valid_session
        expect(assigns(:vic_student)).to be_a(VicStudent)
        expect(assigns(:vic_student)).to be_persisted
      end

      it "redirects to the created vic_student" do
        post :create, {:vic_student => valid_attributes}, valid_session
        expect(response).to redirect_to(VicStudent.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved vic_student as @vic_student" do
        post :create, {:vic_student => invalid_attributes}, valid_session
        expect(assigns(:vic_student)).to be_a_new(VicStudent)
      end

      it "re-renders the 'new' template" do
        post :create, {:vic_student => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested vic_student" do
        vic_student = VicStudent.create! valid_attributes
        put :update, {:id => vic_student.to_param, :vic_student => new_attributes}, valid_session
        vic_student.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested vic_student as @vic_student" do
        vic_student = VicStudent.create! valid_attributes
        put :update, {:id => vic_student.to_param, :vic_student => valid_attributes}, valid_session
        expect(assigns(:vic_student)).to eq(vic_student)
      end

      it "redirects to the vic_student" do
        vic_student = VicStudent.create! valid_attributes
        put :update, {:id => vic_student.to_param, :vic_student => valid_attributes}, valid_session
        expect(response).to redirect_to(vic_student)
      end
    end

    context "with invalid params" do
      it "assigns the vic_student as @vic_student" do
        vic_student = VicStudent.create! valid_attributes
        put :update, {:id => vic_student.to_param, :vic_student => invalid_attributes}, valid_session
        expect(assigns(:vic_student)).to eq(vic_student)
      end

      it "re-renders the 'edit' template" do
        vic_student = VicStudent.create! valid_attributes
        put :update, {:id => vic_student.to_param, :vic_student => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested vic_student" do
      vic_student = VicStudent.create! valid_attributes
      expect {
        delete :destroy, {:id => vic_student.to_param}, valid_session
      }.to change(VicStudent, :count).by(-1)
    end

    it "redirects to the vic_students list" do
      vic_student = VicStudent.create! valid_attributes
      delete :destroy, {:id => vic_student.to_param}, valid_session
      expect(response).to redirect_to(vic_students_url)
    end
  end

end
